<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Revenue Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 13px;
            color: #333;
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        .summary {
            margin-bottom: 20px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        th, td {
            border: 1px solid #aaa;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>

    <h2>Revenue Report</h2>

    <p class="summary">From: {{ $from }} &nbsp;&nbsp; To: {{ $to }}</p>
    <p class="summary">Total Revenue: RWF {{ number_format($total) }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Customer</th>
                <th>Service</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Amount Paid</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bookings as $booking)
                <tr>
                    <td>{{ $booking->id }}</td>
                    <td>{{ $booking->customer->user->name ?? '-' }}</td>
                    <td>{{ $booking->service->name ?? 'Deleted Service' }}</td>
                    <td>{{ $booking->date }}</td>
                    <td>{{ \Carbon\Carbon::parse($booking->time)->format('H:i') }}</td>
                    <td>{{ ucfirst($booking->status) }}</td>
                    <td>
                        @if($booking->deposit_amount && !$booking->is_fully_paid)
                            RWF {{ number_format($booking->deposit_amount) }} (Deposit)
                        @else
                            RWF {{ number_format($booking->service->price ?? 0) }}
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7">No bookings found in this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Report generated by Isiah Nail Bar system – {{ now()->format('Y-m-d H:i') }}
    </div>

</body>
</html>
