<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Provider Performance Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin-bottom: 5px;
        }
        .metrics {
            margin-bottom: 30px;
        }
        .metrics table {
            width: 100%;
            border-collapse: collapse;
        }
        .metrics th, .metrics td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        .chart-placeholder {
            height: 300px;
            text-align: center;
            color: #aaa;
            font-style: italic;
            margin-top: 30px;
        }
        .footer {
            margin-top: 40px;
            font-size: 12px;
            text-align: center;
            color: #888;
        }
    </style>
</head>
<body>

    <div class="header">
        <h2>📊 Provider Performance Report</h2>
        <p>Generated on {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <div class="metrics">
        <table>
            <tr>
                <th>Total Bookings</th>
                <td>{{ $totalBookings }}</td>
            </tr>
            <tr>
                <th>Completed Bookings</th>
                <td>{{ $completedBookings }}</td>
            </tr>
            <tr>
                <th>Completion Rate</th>
                <td>{{ number_format($completionRate, 1) }}%</td>
            </tr>
            <tr>
                <th>Total Revenue</th>
                <td>RWF {{ number_format($totalRevenue) }}</td>
            </tr>
        </table>
    </div>

    <div class="chart-placeholder">
        Revenue chart visualization is available on the web dashboard.
    </div>

    <div class="footer">
        &copy; {{ now()->year }} Isiah Nail Bar | Report generated by system
    </div>

</body>
</html>
