<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Revenue Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 13px;
            color: #333;
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        .summary {
            margin-bottom: 20px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        th, td {
            border: 1px solid #aaa;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>

    <h2>Revenue Report</h2>

    <p class="summary">From: <?php echo e($from); ?> &nbsp;&nbsp; To: <?php echo e($to); ?></p>
    <p class="summary">Total Revenue: RWF <?php echo e(number_format($total)); ?></p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Customer</th>
                <th>Service</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Amount Paid</th>
            </tr>
        </thead>
        <tbody>
            <?php $__empty_1 = true; $__currentLoopData = $bookings; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $booking): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                <tr>
                    <td><?php echo e($booking->id); ?></td>
                    <td><?php echo e($booking->customer->user->name ?? '-'); ?></td>
                    <td><?php echo e($booking->service->name ?? 'Deleted Service'); ?></td>
                    <td><?php echo e($booking->date); ?></td>
                    <td><?php echo e(\Carbon\Carbon::parse($booking->time)->format('H:i')); ?></td>
                    <td><?php echo e(ucfirst($booking->status)); ?></td>
                    <td>
                        <?php if($booking->deposit_amount && !$booking->is_fully_paid): ?>
                            RWF <?php echo e(number_format($booking->deposit_amount)); ?> (Deposit)
                        <?php else: ?>
                            RWF <?php echo e(number_format($booking->service->price ?? 0)); ?>

                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                <tr>
                    <td colspan="7">No bookings found in this period.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        Report generated by Isiah Nail Bar system – <?php echo e(now()->format('Y-m-d H:i')); ?>

    </div>

</body>
</html>
<?php /**PATH C:\Users\mouba\isaiahnailbar\resources\views\dashboard\admin\reports-pdf.blade.php ENDPATH**/ ?>